deploy:
  stage: deploy
  image : agoncaruks/aws-elastic-beanstalk-cli
  script:
    - pip install --upgrade awsebcli
    - eb init -p go projet-pc3r --region $AWS_DEFAULT_REGION 
    - eb deploy projet-pc3r
